### PR TITLE
Bail when in Editor & increase concatenation limit.

### LINKED ISSUE #80713: Editing ToolKit and Page Optimize conflict at [Add New Post] page on sites with heavier plugin use
### Quick summary

Relevant links:

- tracking thread: p9F6qB-d1r-p2 
- escalation: p1692205609474649-slack-C02FMH4G8

When users go to My Site > Pages (posts & custom post types, too) > Add New, they see a broken editor due to a static 400 response on a page-optimized concatenated CSS file. 

While it's typical for Page Optimize's CSS concatenation to cause this issue, there is a significant spike of reports (over 50 on the tracking thread above), and reports are suggesting a possible conflict between the WordPress.com Editing Toolkit and Page Optimize plugins (with a combination of various third-party plugins).

Turning off CSS concatenate within Page Optimize's settings only helps in very few cases, and the entire plugin, either Page Optimize or WordPress.com Editing ToolKit, needs to be deactivated to fix the editor (we've **encouraged deactivating Page Optimize as the work around, since the WordPress.com Editing ToolKit plugin comes with a lot of features**.)

### Steps to reproduce

~~We have been unable to reproduce on a test site. However, the issue is still reproducible on sites within the tracking thread when you turn Page Optimize back on.~~ https://github.com/Automattic/wp-calypso/issues/80713#issuecomment-1681425041.

### What you expected to happen

I expect the editor to load.

### What actually happened

The editor loads with broken CSS, and there's a 400 bad request on one of the Page Optimize CSS files e.g ( `/_static/??-eJy9`) 

image

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes https://github.com/Automattic/wp-calypso/issues/80713

# Description
We're experiencing some issues caused by the page optimizer being loaded on the Editor. You can see the exact error described in the referenced issue or in this conversation p1692205609474649-slack-C02FMH4G8.

After some investigation, I've noticed that we have a hard limit on the number of files that we can concatenate, which is not that hard to hit. With just a dozen Editor plugins we're already reaching the limit.

# Solution
I've increased the limit, now it's 2x the original so that we avoid hitting it as easily. On the other hand, we now bail out and do not load the plugin if we are in the Editor.

# Testing Instructions
- On an Atomic site...
- Add plugins until you can reproduce the error.
- Upload the plugin to your WoA site.
- Open the Editor and with Chrome's developer tools...
- Look at the network tab and filter by `static` you shouldn't see any requests and the Editor should load without errors.
- [Optional] Comment the lines in the plugin that bail and open the Editor, you also should see that the Editor loads correctly and that there is a request when filtering by `static` in Chrome's Network tab.

### CODE REVIEW

File: page-optimize.php [hunk 1]
```diff
@@ -272,6 +272,12 @@ function page_optimize_bail() {
 		return true;
 	}
 
+	// Bail if we're in the editor
+	global $pagenow;
+	if ( isset( $pagenow ) && ( $pagenow == 'post.php' || $pagenow == 'post-new.php' ) ) {
```
Comment (dinhtungdu) [inline page-optimize.php]: Can we also include the site editor as well?

**Comment by BogdanUngureanu** [comment]
I think increasing the limit sounds like a temporary fix. I wonder why had this hard limit in the first place 🤔  Maybe to avoid a performance issue?

What do you think if we create a follow-up PR that concatenates the first X assets and ignores the remaining assets?

File: page-optimize.php (hunk 1 above)
Comment (mmtr) [reply page-optimize.php]: @rcrdortiz You can also check [`WP_Screen::is_block_editor`](https://developer.wordpress.org/reference/classes/wp_screen/is_block_editor/) which should work for all editors:

```php
if ( get_current_screen()->is_block_editor() ) {
  return true;
}
```

**Comment by rcrdortiz** [comment]
> I think increasing the limit sounds like a temporary fix. I wonder why had this hard limit in the first place 🤔 Maybe to avoid a performance issue?
> 
> What do you think if we create a follow-up PR that concatenates the first X assets and ignores the remaining assets?

If we concatenate the first X assets we will have a broken UX/UI so I'm against that.

File: page-optimize.php (hunk 1 above)
Comment (rcrdortiz) [reply page-optimize.php]: I initially tried the `get_current_screen approach` but the result is `null` so we need to check the `$pagenow` instead. I'll create a list of pages to exclude so that we can also exclude the site editor.

Comment (rcrdortiz) [reply page-optimize.php]: Done! We now don't load the plugin when on the Site Editor.

**Review by mmtr — APPROVED** [review]
Works like a charm!

**Comment by BogdanUngureanu** [comment]
> > I think increasing the limit sounds like a temporary fix. I wonder why had this hard limit in the first place 🤔 Maybe to avoid a performance issue?
> > What do you think if we create a follow-up PR that concatenates the first X assets and ignores the remaining assets?
> 
> If we concatenate the first X assets we will have a broken UX/UI so I'm against that.

Oh, good point! The cutoff should be based on plugins, which is harder to determine.

Another idea: What if we disable the concatenation based on the asset count instead of the page they are located? I think it makes more sense because returning a 400 error is not an option in the first place.

**Review by dinhtungdu — APPROVED** [review]
Tested on atomic and can confirm this fix. 🚀

**Comment by mmtr** [comment]
> Another idea: What if we disable the concatenation based on the asset count instead of the page they are located? I think it makes more sense because returning a 400 error is not an option in the first place.

Could be worth considering, but let's discuss that on a separate issue. And to be honest, I think it should be investigated by a different team more familiar with Page Optimize.

**Comment by rcrdortiz** [comment]
> Oh, good point! The cutoff should be based on plugins, which is harder to determine.
Another idea: What if we disable the concatenation based on the asset count instead of the page they are located? I think it makes more sense because returning a 400 error is not an option in the first place.

I think the current implementation is fine. Let's wait for this to be a problem before we try to find a solution. At the moment increasing the limit is a good enough solution.
